"""Remove nationality, document_type, document from users and department, seniority_level from job_titles

Revision ID: 2427c46474a7
Revises: 78db9e06f654
Create Date: 2025-10-11 04:41:32.037036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2427c46474a7'
down_revision: Union[str, Sequence[str], None] = '78db9e06f654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_constraint(op.f('items_category_id_fkey'), 'items', type_='foreignkey')
    op.drop_column('items', 'category_id')
    op.drop_column('job_titles', 'seniority_level')
    op.drop_column('job_titles', 'department')
    op.drop_index(op.f('ix_users_document'), table_name='users')
    op.drop_index(op.f('ix_users_document_type'), table_name='users')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'document')
    op.drop_column('users', 'document_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_document_type'), 'users', ['document_type'], unique=False)
    op.create_index(op.f('ix_users_document'), 'users', ['document'], unique=True)
    op.add_column('job_titles', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('job_titles', sa.Column('seniority_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('items_category_id_fkey'), 'items', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.alter_column('items', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
