"""remove unique constraint from user document_type

Revision ID: 6927b39cf9d2
Revises: da596f402200
Create Date: 2025-09-13 19:21:04.621544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6927b39cf9d2'
down_revision: Union[str, Sequence[str], None] = 'da596f402200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_document_type'), table_name='users')
    op.create_index(op.f('ix_users_document_type'), 'users', ['document_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_document_type'), table_name='users')
    op.create_index(op.f('ix_users_document_type'), 'users', ['document_type'], unique=True)
    # ### end Alembic commands ###
