"""Add year field to public_acquisition

Revision ID: 6b13822d48e8
Revises: d5887220b485
Create Date: 2025-11-06 23:42:59.962262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b13822d48e8'
down_revision: Union[str, Sequence[str], None] = 'd5887220b485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_acquisitions', sa.Column('year', sa.Integer(), nullable=False, server_default='2024'))
    op.create_index(op.f('ix_public_acquisitions_year'), 'public_acquisitions', ['year'], unique=False)
    op.alter_column('public_acquisitions', 'year', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_acquisitions_year'), table_name='public_acquisitions')
    op.drop_column('public_acquisitions', 'year')
    # ### end Alembic commands ###
