"""Update catalog model structure

Revision ID: 78db9e06f654
Revises: 92f28c0a2650
Create Date: 2025-09-28 03:34:50.814272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78db9e06f654'
down_revision: Union[str, Sequence[str], None] = '92f28c0a2650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_category_id'), table_name='catalog')
    op.drop_index(op.f('ix_catalog_internal_code'), table_name='catalog')
    op.drop_index(op.f('ix_catalog_subcategory_id'), table_name='catalog')
    op.drop_constraint(op.f('catalog_category_id_fkey'), 'catalog', type_='foreignkey')
    op.drop_constraint(op.f('catalog_subcategory_id_fkey'), 'catalog', type_='foreignkey')
    op.drop_column('catalog', 'is_active')
    op.drop_column('catalog', 'category_id')
    op.drop_column('catalog', 'internal_code')
    op.drop_column('catalog', 'subcategory_id')
    op.drop_column('catalog', 'sample')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('sample', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('catalog', sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('catalog', sa.Column('internal_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('catalog', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('catalog', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('catalog_subcategory_id_fkey'), 'catalog', 'subcategories', ['subcategory_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('catalog_category_id_fkey'), 'catalog', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_catalog_subcategory_id'), 'catalog', ['subcategory_id'], unique=False)
    op.create_index(op.f('ix_catalog_internal_code'), 'catalog', ['internal_code'], unique=True)
    op.create_index(op.f('ix_catalog_category_id'), 'catalog', ['category_id'], unique=False)
    # ### end Alembic commands ###
