"""Add user_id to public_acquisition

Revision ID: b27c7bae035d
Revises: 6b13822d48e8
Create Date: 2025-11-06 23:57:28.384592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b27c7bae035d'
down_revision: Union[str, Sequence[str], None] = '6b13822d48e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add user_id column with temporary default value
    op.add_column('public_acquisitions', sa.Column('user_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_public_acquisitions_user_id'), 'public_acquisitions', ['user_id'], unique=False)
    op.create_foreign_key(op.f('public_acquisitions_user_id_fkey'), 'public_acquisitions', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    # Remove server default after column is created
    op.alter_column('public_acquisitions', 'user_id', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('public_acquisitions_user_id_fkey'), 'public_acquisitions', type_='foreignkey')
    op.drop_index(op.f('ix_public_acquisitions_user_id'), table_name='public_acquisitions')
    op.drop_column('public_acquisitions', 'user_id')
    # ### end Alembic commands ###
