"""remove unique constraint from hospital document_type

Revision ID: da596f402200
Revises: 7e2f0619b991
Create Date: 2025-09-13 18:58:07.550659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da596f402200'
down_revision: Union[str, Sequence[str], None] = '7e2f0619b991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospitals_document_type'), table_name='hospitals')
    op.create_index(op.f('ix_hospitals_document_type'), 'hospitals', ['document_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospitals_document_type'), table_name='hospitals')
    op.create_index(op.f('ix_hospitals_document_type'), 'hospitals', ['document_type'], unique=True)
    # ### end Alembic commands ###
