"""Add is_holder field to items_public_acquisitions

Revision ID: eef98d8d2f00
Revises: fc928d0acedf
Create Date: 2025-11-07 00:59:23.325841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef98d8d2f00'
down_revision: Union[str, Sequence[str], None] = 'fc928d0acedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_public_acquisitions', sa.Column('is_holder', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items_public_acquisitions', 'is_holder')
    # ### end Alembic commands ###
