"""Add items_public_acquisitions association table

Revision ID: fc928d0acedf
Revises: b27c7bae035d
Create Date: 2025-11-07 00:43:57.777336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc928d0acedf'
down_revision: Union[str, Sequence[str], None] = 'b27c7bae035d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create items_public_acquisitions association table
    op.create_table('items_public_acquisitions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('public_acquisition_id', sa.Integer(), nullable=False),
        sa.Column('supplier_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('items_public_acquisitions_item_id_fkey'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['public_acquisition_id'], ['public_acquisitions.id'], name=op.f('items_public_acquisitions_public_acquisition_id_fkey'), ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('items_public_acquisitions_supplier_id_fkey'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id', name=op.f('items_public_acquisitions_pkey'))
    )
    op.create_index(op.f('ix_items_public_acquisitions_id'), 'items_public_acquisitions', ['id'], unique=False)
    op.create_index(op.f('ix_items_public_acquisitions_item_id'), 'items_public_acquisitions', ['item_id'], unique=False)
    op.create_index(op.f('ix_items_public_acquisitions_public_acquisition_id'), 'items_public_acquisitions', ['public_acquisition_id'], unique=False)
    op.create_index(op.f('ix_items_public_acquisitions_public_id'), 'items_public_acquisitions', ['public_id'], unique=True)
    op.create_index(op.f('ix_items_public_acquisitions_supplier_id'), 'items_public_acquisitions', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_public_acquisitions_supplier_id'), table_name='items_public_acquisitions')
    op.drop_index(op.f('ix_items_public_acquisitions_public_id'), table_name='items_public_acquisitions')
    op.drop_index(op.f('ix_items_public_acquisitions_public_acquisition_id'), table_name='items_public_acquisitions')
    op.drop_index(op.f('ix_items_public_acquisitions_item_id'), table_name='items_public_acquisitions')
    op.drop_index(op.f('ix_items_public_acquisitions_id'), table_name='items_public_acquisitions')
    op.drop_table('items_public_acquisitions')
    # ### end Alembic commands ###
